### ISSUE TITLE
Roadmap: Project Documentation

### ISSUE THREAD

**Issue by slucero** [forumone/generator-web-starter#19]
Project documentation for usage and best practices is lacking currently. Let's explore some of the primary areas that are needed and project a series of tasks to complete.

## Needed Documentation
- [ ] Installing the generator (#15)
- [ ] Starting a new project (#14)
- [ ] Updating and/or reconfiguring an existing project (#16)
- [ ] Project support and contribution (#17)
- [ ] Developer documentation (#18)
