### ISSUE TITLE
Roadmap: Pluggable Generators

### ISSUE THREAD

**Issue by slucero** [forumone/generator-web-starter#24]
The current release of the generator is monolithic and attempts to handle generation for all scenarios within the single `web-starter:app` generator. This has become difficult to maintain and extend.
A more maintainable approach for moving forward would be to allow for new generators to be created and discoverable via a dynamic plug-in architecture.
Following this model, the overall app creation generator would still be available and serve as a generic entry point to the appropriate sub-generators, but the majority of its functionality would be limited to exposing the discovered sub-generators for selection and managing any connections needed between them. All further configuration and activities needed by each sub-generator should be managed and exposed from that specific plugin to keep the overall app handler lean.
Additionally, these sub-generator plugins should be exposed for independent usage for more advanced and intricate customization options as needed without having to navigate the forms for all enabled plugins.

## Roadmap
- [x] Proof of concept
  - _Test implementation and triggering of sub-generator model from an overall entry generator._
- [x] Implement overall app generator with plugin discovery model.
- [x] Decompose existing generator features into new plug-in model.
  - [x] Puppet
  - [x] Capistrano
  - [x] Drupal
  - [x] Wordpress

**Comment by slucero** [comment]
@wwhurley, when you get a chance please look this over to make sure it's still in line with your understanding of our discussion.

**Comment by wwhurley** [comment]
Created initial scaffolding in the separating-generators branch. It has a dependency on forumone/generator-web-starter-drupal project.

**Comment by wwhurley** [comment]
Added brief instructions on creating a web-starter plugin at https://github.com/forumone/generator-web-starter/wiki/Create-a-plugin

**Comment by slucero** [comment]
This looks great @wwhurley! This sets up a strong infrastructure for us to follow and build on top of!
I think one of the tricky parts, but by no means deal-breaking, is that currently the model requires all plugins to be registered in the `package.json` file and installed. I think this is fine early on as we'll only have a handful of generators, but I don't know how manageable it'll stay as we expand and ideally get more plugins written.
If I'm correctly reading the documentation for [Yeoman Environment](http://yeoman.github.io/environment/) it looks like it'll discover the plugins as long as they're installed regardless whether they're represented in the `package.json`, correct? This could bring the problem into the realm of documentation and indexing of existing plugins, but we may just want to stay aware for a more tenable solution.

**Comment by wwhurley** [comment]
Right now the generator will discover any sub-generators that are named 'web-starter'. My intention is to have the sub-generators that we use consistently would be hard dependencies to the basic generator so we don't have to lead folks through installing 5 or 6 NPM modules.

**Comment by wwhurley** [comment]
Fixed issue with local dependencies in #27.
